---
title: "My Fellowship Experience: Part 2"
categories:
  - fellowship 
  - analytics
  - job
description: |
  What I've learned four months into my analytics fellowship.
author:
  - name: Danielle Brantley
    url: https://gist.github.com/danielle-b
date: 03-05-2021
output:
  distill::distill_article:
    self_contained: false
draft: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

February 12 marked four months since I started an analytics fellowship at a digital agency. Since my [last post](https://datascidani.com/posts/2020-12-16-my-fellowship-experience-what-ive-learned-so-far/), I am continuing to learn more about the role of an analyst, however I am also learning where my interests lie. In honor of me reaching the four month mark, I decided to share what I've learned about this role and about myself.  

**Spreadsheets** <br>
  In my role, I work with Excel and Google Sheets extensively. I mean everyday, multiple times a day. I have noticed that my job prefers Google Sheets. Almost all of the dashboards I interact with are built in Google Sheets(others are in Data Studio) and much of the reports I submit are in Google Sheets. I have never had a role where I had to use spreadsheets so much before and it has been a learning experience. I decided to learn more shortcuts and formulas via the [Google Sheets - The Comprehensive Masterclass](https://www.udemy.com/course/google-sheets-masterclass/) course on Udemy that will enhance my workflow with spreadsheets.
  
**SQL** <br>
  Since the last post, I have found myself using SQL. Over the last couple of weeks, my work has been SQL heavy. This was partly the reason why I enrolled in the MYSQL Bootcamp course on [Udemy](https://www.udemy.com/course/the-ultimate-mysql-bootcamp-go-from-sql-beginner-to-expert/). I am happy to say that I am almost finished with the course! I am really enjoying SQL and I can't wait to learn more advanced topics. I think the reason why I was so happy to get into SQL was because it brought me back to coding which brings me to my next point.

**I Miss Coding** <br>
  I never thought I'd say this but I actually miss coding. Aside from SQL, I don't get to do much coding. I decided to practice more programming outside of work and I have decided to shift gears a bit. If you follow me on Twitter or read my blog, you know that I really enjoy R. I feel R was very helpful in me grasping some of the programming concepts that I wasn't able to grasp in other programming languages. Though I will continue to use R, I've decided to shift my focus away from R (for right now) and focus more on Python and SQL. I starting learning Python before deciding to focus on R but I think I'm ready to return to it. I think having Python, SQL, R (as well as dashboarding tools) in my toolkit will help me tremendously when looking for roles. 
  
**Interests are Shifting** <br>
 When I first filled out the application for the analytics fellowship, I expressed that I wanted to start out as a data analyst and eventually move into a Data Scientist role. That was back in August. Since then, I have found that my interests are changing a bit. Though I have found that I enjoy analytics and would like to continue in a data analyst role, I'm not so sure about me being a data scientist. Though I find statistics and some areas of machine learning fascinating, I find that I'm more interested in learning about data flow and transformation of data.
 
**Data Engineering** <br>
   While I'm not so sure about me being a data scientist, one area that has been an interest of mine is data engineering. I find that the projects I've enjoyed the most during my fellowship use [Frakture](https://www.frakture.com/) and [MYSQL](https://dev.mysql.com/doc/refman/8.0/en/) to pull data for reporting while using [MYSQL Workbench](https://www.mysql.com/products/workbench/) as the IDE. I was exposed to [dbt](https://docs.getdbt.com/docs/introduction) and [Google BigQuery](https://cloud.google.com/bigquery/docs) during a team meeting a few months back but do not use them in my day to day work. I was recently onboarded to a client where those tools are used so I am hoping to this changes and I learn a lot more about how they work. If you read my most recent tweets, you've seen me ask for any data engineering resources. Since then I've come across the [Awesome Data Engineering](https://awesomedataengineering.com/) website and will be looking through this site during my free time. I would love to know more the work of a data engineer. I want to know what their day-to-day is like, what their process is like. What are some important data engineering concepts I should know? What exactly is their role? What are the tasks that data engineers are in charge of? I'd love to know what tools they use and how they work. If you know of a data engineer or if you are a data engineer yourself, I'd love some more resources.
  
Whew! That's all I got right now!
  
I'll probably do another post at the six month mark (when my fellowship ends). Then I can share my overall experience.

Until next time...


