---
title: "Quarantining and Things"
categories:
  - data science 
  - programming
  - R
  - quarantine
description: |
  What I've been going through in quarantine.
base_url: https://datascidani.com/2020/04/08/quarantining-and-things/
author:
  - name: Danielle Brantley
    url: https://gist.github.com/danielle-b
date: 04-08-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

It’s been a minute since I last posted any content on my DataQuest track. So I thought I’d tell you what’s been going on.

I decided to take a break because I haven’t felt like my productive self. I found myself feeling really sad with all the COVID-19 news. I was unemployed looking for work before this quarantine and I’m still unemployed but now I just feel like, will I ever find a job? On top of this, I felt a bit discouraged about my blog, questioning my abilities, whether or not blogging would actually help me in my transition into a data science career. I constantly asked myself, am I wasting my time? Is all of this in vain? I am also facing difficulty with learning to do data cleaning using R which has slowed me down a bit however, this issue is rather minor compared to the ones I just mentioned.

However, I’m slowly starting to get back to my normal productive self. I continue to learn R using the DataQuest platform. Data cleaning is an essential part of the data analysis process so it’s important to me that I become proficient with this part of the track. One of my blog posts, Scatter Plots, was included in the [Code With Veni](https://www.getrevue.co/profile/codewithveni/issues/complete-guide-to-acing-remote-interviews-an-introduction-to-python-programming-for-beginners-i-m-tired-of-being-superwoman-235097) newsletter which was a huge confidence booster. I nearly cried when I found out my post was included. I can’t explain what an honor it was to be included in a newsletter with other awesome coders. I like to thank DiKayo Data for bringing the newsletter to my attention and Veni for including me. Speaking of Dikayo Data, I participated in her #DataEveryone chat on Tuesday which always lifts my spirits and I leave the chat learning more then when I entered.

Some of the meetups that I had previously planned to attend are now online and I plan on attending those. I also decided to take advantage of the free month of nanodegrees Udacity announced and enrolled in their Marketing Analytics Nanodegree. It focuses on learning to analyze data and building models with Excel, Data Studio, and creating data visualizations with Tableau. I thought it would be a nice complement to the Data Analyst track which focuses on R and SQL. I’ve already completed the first two sections which focuses on Descriptive Statistics which I really enjoyed.

I’ve have really become interested in Statistics as of late. I saved some e-books I found on Stats, particularly those that focus on R. I’m also at the beginning of Naked Statistics by Charles Wheelan. I think this interest in Statistics started with my Business Statistics class in undergrad. Back then, I did not understand what was being taught and as a result, did not do well in the class. But I held on to the textbook thinking that one day I would revisit it and teach myself Stats. With Statistics being an important component of Data Science, I figured this is the opportunity to learn it. Everything going on with COVID-19 also has something to do with it. With so much data surrounding this pandemic and this data being in our faces constantly, I want to be able to understand the data and how certain numbers and conclusions are derived. And so here I am revisiting things like standard deviation and variance and learning about correlation and regression.

I apologize if this sounds like a bunch of random thoughts but I had to get this out. I wanted to share what I’m going through. But the lessons I have learned through all this are that it is okay to not be productive. It’s okay to feel unmotivated. It’s okay to mourn plans that fell through. Especially during these trying times. As for me, I want to use this time to reassesses my habits and goals and I’ve put some thought into life after this crisis. I’m remembering to breathe, take my time and do things at my own pace.



